/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class Keywords: Object {

  enum Attributes: String {
    case keyword = "keyword"
  }

  dynamic var keyword: String = ""

}
