/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class Task: Object {

  enum Attributes: String {
    case dateEnd = "dateEnd"
    case dateStart = "dateStart"
    case delayed = "delayed"
    case desc = "desc"
    case fileUrl = "fileUrl"
    case name = "name"
    case progress = "progress"
    case status = "status"
    case time = "time"
  }

  enum Relationships: String {
    case keywords = "keywords"
  }

  dynamic var dateEnd: Date?
  dynamic var dateStart: Date?
  var delayed = RealmOptional<Bool>()
  dynamic var desc: String?
  dynamic var fileUrl: String = ""
  dynamic var name: String = ""
  var progress = RealmOptional<Float>()
  var status = RealmOptional<Int16>()
  var time = RealmOptional<Double>()
  var keywords = List<Keywords>()

  override static func primaryKey() -> String? {
    return "fileUrl"
  }

}
