/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class Task: Object {

  enum Attributes: String {
    case dateEnd = "dateEnd"
    case dateStart = "dateStart"
    case delayed = "delayed"
    case desc = "desc"
    case fileUrl = "fileUrl"
    case id = "id"
    case keywords = "keywords"
    case name = "name"
    case status = "status"
    case time = "time"
  }

  dynamic var dateEnd: Date?
  dynamic var dateStart: Date?
  var delayed = RealmOptional<Bool>()
  dynamic var desc: String?
  dynamic var fileUrl: String?
  dynamic var id: Int64 = 0
  var keywords: List<String>?
  dynamic var name: String = ""
  var status = RealmOptional<Int16>()
  var time = RealmOptional<Int64>()

  override static func primaryKey() -> String? {
    return "id"
  }

}
