/* DO NOT EDIT | Generated by gyro */

import RealmSwift
import Foundation

final class Task: Object {

  enum Attributes: String {
    case dateEnd = "dateEnd"
    case dateStart = "dateStart"
    case delayed = "delayed"
    case desc = "desc"
    case keywords = "keywords"
    case name = "name"
    case status = "status"
    case time = "time"
  }

  dynamic var dateEnd: Date?
  dynamic var dateStart: Date?
  let delayed = RealmOptional<Bool>()
  dynamic var desc: String?
  dynamic var keywords: [String]?
  dynamic var name: String?
  let status = RealmOptional<Int16>()
  let time = RealmOptional<Int64>()

}
